export * from './login-type'
export * from './identitas-type'
export * from './jalur-masuk-type'
export * from './gelombang-type'
export * from './sekilas-type'
export * from './aturan-type'
export * from './jadwal-type'
export * from './lokasi-type'
